### PR TITLE
Version 0.4.0

### PR DESCRIPTION
**Pull request by eagletmt**
For convenience in making a package for Linux.

@sorah ?

### CODE REVIEW

**Comment by sorah** [comment]
oh, I'm planned to do within this few hours: http://twitter.com/sora_h/status/740505244996501504

**Comment by sorah** [comment]
I want to fix README a bit before a release

**Comment by sorah** [comment]
Released as v1.0.0 :pray:

**Comment by eagletmt** [comment]
:tada:

**Pull request closed without merging**
