### PR TITLE
Cleanup Makefile and use travis for builds

### PR DESCRIPTION
**Pull request by stephengroat**
[Here's an example of what travis looks like](https://travis-ci.org/stephengroat/envchain/builds/339290933)

### CODE REVIEW

**Comment by sorah** [comment]
Thanks. What's your background behind this PR?

**Comment by stephengroat** [comment]
@sorah just trying to do some cleanup and automate builds

**Comment by stephengroat** [comment]
any desire for this? trying to cleanup some open PRs

this is mainly a very effective use of Make defaults/norms and CI/CD testing

**Comment by sorah** [comment]
You can send a patch without having a CI, I'll wait for a patch first.

Even there's no test suite, I understand it might be useful to check builds on other platforms, but... sorry, I don't want to use Travis CI at this moment and I don't want to accept a PR to just introduce CI (unless you really have a patch to fix or enhance something).

**Pull request closed without merging**
